// <auto-generated />
using Discount.gRPC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.gRPC.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20241129203656_dataseed")]
    partial class dataseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Discount.gRPC.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductName")
                        .IsUnique();

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 150,
                            Description = "IPhone Discount",
                            ProductName = "IPhone X"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100,
                            Description = "Samsung Discount",
                            ProductName = "Samsung 10"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 120,
                            Description = "Google Pixel Discount",
                            ProductName = "Google Pixel 6"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 90,
                            Description = "OnePlus Discount",
                            ProductName = "OnePlus 9"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 80,
                            Description = "Sony Discount",
                            ProductName = "Sony Xperia 5"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 70,
                            Description = "LG Discount",
                            ProductName = "LG Velvet"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 60,
                            Description = "Motorola Discount",
                            ProductName = "Motorola Edge"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 110,
                            Description = "Huawei Discount",
                            ProductName = "Huawei P40"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 50,
                            Description = "Nokia Discount",
                            ProductName = "Nokia 8.3"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 85,
                            Description = "Xiaomi Discount",
                            ProductName = "Xiaomi Mi 11"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 95,
                            Description = "Oppo Discount",
                            ProductName = "Oppo Find X3"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 65,
                            Description = "Vivo Discount",
                            ProductName = "Vivo X60"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 75,
                            Description = "GT Discount",
                            ProductName = "GT"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 130,
                            Description = "Asus Discount",
                            ProductName = "Asus ROG Phone 5"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 115,
                            Description = "Lenovo Discount",
                            ProductName = "Lenovo Legion Duel"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 105,
                            Description = "Black Shark Discount",
                            ProductName = "Black Shark 4"
                        },
                        new
                        {
                            Id = 17,
                            Amount = 55,
                            Description = "ZTE Discount",
                            ProductName = "ZTE Axon 30"
                        },
                        new
                        {
                            Id = 18,
                            Amount = 200,
                            Description = "MacBook Discount",
                            ProductName = "Apple MacBook Pro"
                        },
                        new
                        {
                            Id = 19,
                            Amount = 180,
                            Description = "Dell Discount",
                            ProductName = "Dell XPS 13"
                        },
                        new
                        {
                            Id = 20,
                            Amount = 170,
                            Description = "HP x360 Discount",
                            ProductName = "HP x360"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
