
services:
  basket.db:
    image: postgres
  catalog.db:
    image: postgres
  ordering.db:
    image: mcr.microsoft.com/mssql/server:latest
  hybridcache:
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount.gRPC/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: Services
      dockerfile: Ordering/Ordering.API/Dockerfile

volumes:
  catalog_volume:
  basket_volume:
  ordering_volume:




