# This is a generated file. Not intended for manual editing.
services:
  basket.api:
    build:
      context: "C:\\Users\\x3010\\OneDrive\\Desktop\\EcommerceMicroservices\\src"
      dockerfile: "Services/Basket.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "basketapi:dev"
    ports:
    - "127.0.0.1:57000:57000"
    - "127.0.0.1:57200:57200"
    - "127.0.0.1:57400:57400"
    volumes:
    - "C:\\Users\\x3010\\OneDrive\\Desktop\\EcommerceMicroservices\\src\\Services\\\
      Basket.API:/app:rw"
    - "C:\\Users\\x3010\\OneDrive\\Desktop\\EcommerceMicroservices\\src:/src:rw"
    - "C:\\Users\\x3010\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\x3010\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.4\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.4\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\x3010\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_2_19_02_27_54:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  catalog.api:
    build:
      context: "C:\\Users\\x3010\\OneDrive\\Desktop\\EcommerceMicroservices\\src"
      dockerfile: "Services/Catalog.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "catalogapi:dev"
    ports:
    - "127.0.0.1:57001:57000"
    - "127.0.0.1:57201:57200"
    - "127.0.0.1:57401:57400"
    volumes:
    - "C:\\Users\\x3010\\OneDrive\\Desktop\\EcommerceMicroservices\\src\\Services\\\
      Catalog.API:/app:rw"
    - "C:\\Users\\x3010\\OneDrive\\Desktop\\EcommerceMicroservices\\src:/src:rw"
    - "C:\\Users\\x3010\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\x3010\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.4\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.4\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\x3010\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_2_19_02_27_54:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  discount.grpc:
    build:
      context: "C:\\Users\\x3010\\OneDrive\\Desktop\\EcommerceMicroservices\\src"
      dockerfile: "Services/Discount.gRPC/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "discountgrpc:dev"
    ports:
    - "127.0.0.1:57002:57000"
    - "127.0.0.1:57202:57200"
    - "127.0.0.1:57402:57400"
    volumes:
    - "C:\\Users\\x3010\\OneDrive\\Desktop\\EcommerceMicroservices\\src\\Services\\\
      Discount.gRPC:/app:rw"
    - "C:\\Users\\x3010\\OneDrive\\Desktop\\EcommerceMicroservices\\src:/src:rw"
    - "C:\\Users\\x3010\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\x3010\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.4\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.4\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\x3010\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_2_19_02_27_54:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  ordering.api:
    build:
      context: "C:\\Users\\x3010\\OneDrive\\Desktop\\EcommerceMicroservices\\src"
      dockerfile: "Services/Ordering/Ordering.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "orderingapi:dev"
    ports:
    - "127.0.0.1:57003:57000"
    - "127.0.0.1:57203:57200"
    - "127.0.0.1:57403:57400"
    volumes:
    - "C:\\Users\\x3010\\OneDrive\\Desktop\\EcommerceMicroservices\\src\\Services\\\
      Ordering\\Ordering.API:/app:rw"
    - "C:\\Users\\x3010\\OneDrive\\Desktop\\EcommerceMicroservices\\src:/src:rw"
    - "C:\\Users\\x3010\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\x3010\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.4\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.4\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\x3010\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_2_19_02_27_54:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
