# This is a generated file. Not intended for manual editing.
services:
  basket.api:
    build:
      context: "C:\\Users\\x3010\\source\\repos\\EcommerceMicroservices\\src"
      dockerfile: "Services/Basket.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Basket.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "basketapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\x3010\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\x3010\\source\\repos\\EcommerceMicroservices\\src\\Services\\Basket.API:/app:rw"
    - "C:\\Users\\x3010\\source\\repos\\EcommerceMicroservices\\src:/src:rw"
    working_dir: "/app"
  catalog.api:
    build:
      context: "C:\\Users\\x3010\\source\\repos\\EcommerceMicroservices\\src"
      dockerfile: "Services/Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Catalog.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\x3010\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\x3010\\source\\repos\\EcommerceMicroservices\\src\\Services\\Catalog.API:/app:rw"
    - "C:\\Users\\x3010\\source\\repos\\EcommerceMicroservices\\src:/src:rw"
    working_dir: "/app"
